# Generated by Django 4.2.4 on 2023-11-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'artist_table',
            },
        ),
    ]
