# Generated by Django 4.2.4 on 2023-11-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
