# Generated by Django 4.2.4 on 2023-09-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adminpage_table',
            },
        ),
    ]
