# Generated by Django 4.2.4 on 2023-10-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_adminpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPage',
        ),
    ]
