# Generated by Django 4.2.4 on 2023-10-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
