# Generated by Django 4.2.4 on 2023-10-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
