# Generated by Django 4.2.4 on 2023-10-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerapp', '0006_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('feedback', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'FeedBack',
            },
        ),
    ]
