# Generated by Django 4.2.4 on 2023-11-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
