# Generated by Django 4.2.4 on 2023-11-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0010_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
