# Generated by Django 4.2.4 on 2023-11-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0012_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
