# Generated by Django 4.2.4 on 2023-11-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0015_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('altphone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
